# mamba env update -f ./environment.yml --prune
# The `- -e .` option under `- pip:` installs `avoidable_admissions` as a local development package
# This allows easier importing without having to add the avoidable_admissions folder to PATH.
name: hdruk_aa
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - holoviews
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - nbstripout
  - pandas
  - pandas-profiling
  - pandera
  - pip
  - pre-commit
  - python-dotenv
  - python>=3.11
  - seaborn
  # Uncomment these lines and update environment as analytics advances
  # - scikit-learn
  # - scipy
  # - statsmodels
  - pip:
      - -e .
