# mamba env update -f ./environment.yml --prune
# The `- -e .` option under `- pip:` installs `avoidable_admissions` as a local development package
# This allows easier importing without having to add the avoidable_admissions folder to PATH.
name: hdruk_aa
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - black
  - bokeh=2.4.*
  - bs4
  - holoviews=1.15.*
  - html5lib
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - lxml
  - mkdocs
  - mkdocstrings>=0.20
  - mkdocstrings-python
  - nbstripout
  - pandas
  # - pandas-profiling>=3.6 # Does not work with Python 3.11. See Readme.md
  - pandera
  - pip
  - pre-commit
  - python-dotenv
  - seaborn
  - yaml
  - requests_cache
  # Uncomment these lines and update environment as analytics advances
  # - scikit-learn
  # - scipy
  # - statsmodels
  - pip:
      - -e .
