site_name: HDRUK Avoidable Admissions
site_url: https://lthtr-dst.github.io/hdruk_avoidable_admissions/
repo_url: https://github.com/lthtr-dst/hdruk_avoidable_admissions
repo_name: GitHub
site_description: >
  [HDRUK](https://www.hdruk.ac.uk/) Data Science Collaboration on Avoidable Admissions in the NHS.
  Led by [School for Health and Related Research](https://www.sheffield.ac.uk/scharr) as Sheffield University.
site_author: https://github.com/lthtr-dst/
theme:
  name: material
  logo: logo.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
- search
- mkdocstrings
- autorefs
nav:
- Home: index.md
- Analysis Pipeline: pipeline.md
- Data Validation: validation.md
# - Validation Schema: schema.md
- Feature Engineering: features.md
watch:
  - avoidable_admissions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
